sonar.projectKey=blink-debit-api-client-php
sonar.organization=blinkpay
sonar.projectName=blink-debit-api-client-php

sonar.sources=src,config
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=build/coverage.xml
sonar.php.tests.reportPath=build/junit.xml

sonar.exclusions=vendor/**
